name: "Deploy Shuttle.rs project"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "assets/**"
      - "src/**"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo binstall binaries
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-binaries
        restore-keys: |
          ${{ runner.os }}-cargo-binaries
    
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@v1.15.5

    - name: Install cargo-shuttle
      run: cargo binstall cargo-shuttle -y
      shell: bash
      
    - name: Install wasm-pack
      run: cargo binstall wasm-pack -y
      shell: bash

    - name: Build wasm projects
      run: make all
      shell: bash

    - name: Login to shuttle
      run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}
      shell: bash

    - name: Deploy to shuttle
      run: cargo shuttle deploy --name website
      shell: bash
      working-directory: "./"
